-- FASE 4.1 — Campos adicionales de Equipos y Mantenimiento (aditivo).
ALTER TABLE equipment
  ADD COLUMN IF NOT EXISTS code VARCHAR(60),
  ADD COLUMN IF NOT EXISTS brand VARCHAR(80),
  ADD COLUMN IF NOT EXISTS model VARCHAR(80),
  ADD COLUMN IF NOT EXISTS serial VARCHAR(80),
  ADD COLUMN IF NOT EXISTS location VARCHAR(120);

ALTER TABLE equipment_maintenance
  ADD COLUMN IF NOT EXISTS reported_failure TEXT,
  ADD COLUMN IF NOT EXISTS diagnosis TEXT,
  ADD COLUMN IF NOT EXISTS work_done TEXT,
  ADD COLUMN IF NOT EXISTS parts_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS labor_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS other_cost NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS responsible VARCHAR(120),
  ADD COLUMN IF NOT EXISTS next_maintenance_date DATE,
  ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'COMPLETADO';
